import React, { useMemo } from 'react';
import { Alert, Share, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import QRCode from 'qrcode';

const blue='#087FB7', ink='#111827', pale='#F4F7F9', muted='#87919A';
export default function ReceiveScreen({go}:{go:(s:any)=>void}){
  const qr=useMemo(()=>QRCode.create('prava://pay?uid=PRAVA-7F42A9&phone=%2B919000000000&currency=INR'),[]);
  return <ScrollView contentContainerStyle={s.content}><View style={s.header}><TouchableOpacity onPress={()=>go('home')} style={s.back}><Ionicons name="chevron-back" size={24} color={ink}/></TouchableOpacity><View><Text style={s.title}>Receive money</Text><Text style={s.caption}>EXPLORE WHAT'S NEW</Text></View><View style={s.avatar}><Text>🧑🏽</Text></View></View><View style={s.hero}><Ionicons name="qr-code-outline" size={52} color={blue}/></View><Text style={s.bigTitle}>Receive money</Text><Text style={s.sub}>Share your PRAVA QR code</Text><View style={s.qrCard}><View style={s.grid}>{Array.from({length:qr.modules.size},(_,y)=>Array.from({length:qr.modules.size},(_,x)=><View key={`${x}-${y}`} style={[s.cell,{width:230/qr.modules.size,height:230/qr.modules.size,backgroundColor:qr.modules.get(x,y)?'#111':'#fff'}]}/>))}</View><Text style={s.handle}>@prava_user</Text><Text style={s.qrHint}>UID · PRAVA-7F42A9  ·  INR wallet</Text></View><View style={s.options}><Action icon="share-outline" title="Share payment link" sub="Send your QR and PRAVA handle" onPress={()=>Share.share({message:'Pay me on PRAVA: @prava_user · UID PRAVA-7F42A9'})}/><Action icon="receipt-outline" title="Send invoice / request" sub="Create a payment request with an amount" onPress={()=>Alert.alert('Request money','Invoice creation will open when your account is connected to a payment provider.')}/><Action icon="call-outline" title="Receive by phone or UID" sub="+91 90000 00000 · PRAVA-7F42A9" onPress={()=>Share.share({message:'PRAVA UID: PRAVA-7F42A9 · Phone: +91 90000 00000'})}/></View></ScrollView>
}
function Action({icon,title,sub,onPress}:{icon:any,title:string,sub:string,onPress:()=>void}){return <TouchableOpacity style={s.action} onPress={onPress}><Ionicons name={icon} size={23} color={ink}/><View style={{flex:1,marginLeft:14}}><Text style={s.actionTitle}>{title}</Text><Text style={s.actionSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={20} color={muted}/></TouchableOpacity>}
const s=StyleSheet.create({content:{padding:22,paddingBottom:60,backgroundColor:pale},header:{height:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:40,height:40,borderRadius:20,backgroundColor:'#E5EAED',alignItems:'center',justifyContent:'center'},title:{fontSize:23,fontWeight:'800',color:ink},caption:{fontSize:11,color:muted,letterSpacing:1,marginTop:3},avatar:{width:42,height:42,borderRadius:21,backgroundColor:'#D5EEF7',alignItems:'center',justifyContent:'center'},hero:{width:100,height:100,borderRadius:50,backgroundColor:'#D9EFF7',alignItems:'center',justifyContent:'center',alignSelf:'center',marginTop:28},bigTitle:{textAlign:'center',fontSize:29,fontWeight:'800',color:ink,marginTop:20},sub:{textAlign:'center',fontSize:15,color:muted,marginTop:7,marginBottom:24},qrCard:{backgroundColor:'#fff',borderRadius:20,alignItems:'center',padding:20},grid:{width:230,height:230,flexDirection:'row',flexWrap:'wrap',alignContent:'flex-start'},cell:{},handle:{fontSize:20,fontWeight:'800',color:ink,marginTop:15},qrHint:{fontSize:12,color:muted,marginTop:5},options:{marginTop:18},action:{backgroundColor:'#fff',borderRadius:17,padding:17,flexDirection:'row',alignItems:'center',marginBottom:10},actionTitle:{fontSize:15,fontWeight:'800',color:ink},actionSub:{fontSize:12,color:muted,marginTop:4}});
